/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ColorScale,
  Range,
} from './utils/utils';

export namespace Components {
  interface StrcScaleogram {
    /**
    * Data as string of a JSON array of arrays of numbers.
    */
    'data': string;
    /**
    * Boolean if scale should be inverted as a string.
    */
    'invertScale': string;
    /**
    * Color scale as string in Chroma.js format.
    */
    'scale': string;
  }
  interface StrcScaleogramLegend {
    /**
    * Color scale of the legend.
    */
    'colorScale': ColorScale;
    /**
    * Range of the legend.
    */
    'range': Range;
  }
}

declare global {


  interface HTMLStrcScaleogramElement extends Components.StrcScaleogram, HTMLStencilElement {}
  var HTMLStrcScaleogramElement: {
    prototype: HTMLStrcScaleogramElement;
    new (): HTMLStrcScaleogramElement;
  };

  interface HTMLStrcScaleogramLegendElement extends Components.StrcScaleogramLegend, HTMLStencilElement {}
  var HTMLStrcScaleogramLegendElement: {
    prototype: HTMLStrcScaleogramLegendElement;
    new (): HTMLStrcScaleogramLegendElement;
  };
  interface HTMLElementTagNameMap {
    'strc-scaleogram': HTMLStrcScaleogramElement;
    'strc-scaleogram-legend': HTMLStrcScaleogramLegendElement;
  }
}

declare namespace LocalJSX {
  interface StrcScaleogram {
    /**
    * Data as string of a JSON array of arrays of numbers.
    */
    'data'?: string;
    /**
    * Boolean if scale should be inverted as a string.
    */
    'invertScale'?: string;
    /**
    * Color scale as string in Chroma.js format.
    */
    'scale'?: string;
  }
  interface StrcScaleogramLegend {
    /**
    * Color scale of the legend.
    */
    'colorScale'?: ColorScale;
    /**
    * Range of the legend.
    */
    'range'?: Range;
  }

  interface IntrinsicElements {
    'strc-scaleogram': StrcScaleogram;
    'strc-scaleogram-legend': StrcScaleogramLegend;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'strc-scaleogram': LocalJSX.StrcScaleogram & JSXBase.HTMLAttributes<HTMLStrcScaleogramElement>;
      'strc-scaleogram-legend': LocalJSX.StrcScaleogramLegend & JSXBase.HTMLAttributes<HTMLStrcScaleogramLegendElement>;
    }
  }
}


